# Take a pre-built Spring fat jar and optimise for IBM Liberty

FROM openliberty/open-liberty:springBoot2-ubi-min as staging

ARG TARGET_JAR="target/*.jar"

USER root
ADD $TARGET_JAR /staging/fat_app.jar

RUN springBootUtility thin \
      --sourceAppPath=/staging/fat_app.jar \
      --targetThinAppPath=/staging/thin_app.jar \
      --targetLibCachePath=/staging/lib.index.cache

FROM openliberty/open-liberty:springBoot2-ubi-min

USER root
COPY --from=staging /staging/lib.index.cache /opt/ol/wlp/usr/shared/resources/lib.index.cache
COPY --from=staging /staging/thin_app.jar /config/dropins/spring/thin_app.jar

RUN chown -R 1001:0 /config && \
    chmod -R g+rw /config && \
    chown -R 1001:0 /opt/ol/wlp/usr/shared/resources/lib.index.cache && \
    chmod -R g+rw /opt/ol/wlp/usr/shared/resources/lib.index.cache

USER 1001
